name: Quality pipeline

on: [push]

jobs:
  verify-mssql:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup MSSQL
        uses: ./
        with:
          who-to-greet: 'Mona the Octocat'

      - name: Test setup
        run: echo "TBD"

  verify-postgresql:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PostgreSQL
        uses: ./
        with:
          who-to-greet: 'Mona the Octocat'

      - name: Test setup
        run: echo "TBD"