name: Quality pipeline

on: [push]

jobs:
  verify-mssql:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup MSSQL
        uses: ./
        with:
          image: 'mcr.microsoft.com/mssql/server:2019-latest'
          port: 1433
          username: sa
          password: Pa$$w0rd
          database: testdb

      - name: Test setup
        run: echo "TBD"

  verify-postgresql:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PostgreSQL
        uses: ./
        with:
          image: 'mcr.microsoft.com/mssql/server:2019-latest'
          port: 5432
          username: postgres
          password: postgres
          database: testdb

      - name: Test setup
        run: echo "TBD"