name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: Desired version to release (vX.Y.Z)
        required: false

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install NodeJS 14
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install
        run: npm install

      - name: Lint
        run: npm run lint
